"""
Phase 5: Export TBox

Exports the final TBox with usefulness scores to:
1. OWL file (Manchester Syntax)
2. JSON summary report
3. (Optional) LanceDB storage

This is a simplified version for the federated pipeline.
For full OWL export, reuse primitive_tbox/nodes/export_tbox.py
"""

import json
import os
from datetime import datetime
from typing import Dict, Any, List

from loguru import logger

from core.paths import lake_data_path
from workflows.common.node_decorators import graph_node
from workflows.conceptualization.state import FederatedPrimitiveTBoxState


@graph_node(node_type="finalization", log_level="INFO")
def export_tbox_node(state: FederatedPrimitiveTBoxState) -> Dict[str, Any]:
    """
    Phase 5: Export final TBox with usefulness scores.
    
    Outputs:
        1. OWL Manchester Syntax file
        2. JSON report with scores and synthesis history
    """
    logger.info("Phase 5: Export TBox")
    
    final_tbox = state.current_tbox
    if not final_tbox:
        logger.error("  No TBox to export")
        return {
            "export_success": False,
            "export_error": "No TBox available",
        }
    
    classes = final_tbox.get("classes", [])
    data_properties = final_tbox.get("data_properties", [])
    
    logger.info(f"  Exporting: {len(classes)} classes, {len(data_properties)} DataProperties")
    
    # Prepare output directory
    output_dir = _prepare_output_dir(state)
    
    # ========== Generate OWL Manchester Syntax ==========
    owl_content = _generate_manchester_owl(
        classes=classes,
        data_properties=data_properties,
        domain=state.dataset_name,
        aggregated_votes=state.aggregated_votes or {},
    )
    
    owl_path = os.path.join(output_dir, "federated_primitive_tbox.omn")
    with open(owl_path, "w") as f:
        f.write(owl_content)
    logger.info(f"  Saved OWL: {owl_path}")
    
    # ========== Generate JSON Report ==========
    report = _generate_report(
        state=state,
        classes=classes,
        data_properties=data_properties,
    )
    
    report_path = os.path.join(output_dir, "federated_tbox_report.json")
    with open(report_path, "w") as f:
        json.dump(report, f, indent=2, default=str)
    logger.info(f"  Saved report: {report_path}")
    
    return {
        "export_success": True,
        "owl_path": owl_path,
        "report_path": report_path,
        "export_stats": {
            "n_classes": len(classes),
            "n_data_properties": len(data_properties),
            "n_iterations": len(state.synthesis_log or []),
        },
    }


# ============== Helper Functions ==============

def _prepare_output_dir(state: FederatedPrimitiveTBoxState) -> str:
    """Prepare output directory for exports."""
    base_dir = lake_data_path("tbox")
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    dataset = state.dataset_name or "unknown"
    output_dir = os.path.join(base_dir, f"federated_{dataset}_{timestamp}")
    
    os.makedirs(output_dir, exist_ok=True)
    return output_dir


def _generate_manchester_owl(
    classes: List[Dict],
    data_properties: List[Dict],
    domain: str,
    aggregated_votes: Dict[str, float],
) -> str:
    """Generate OWL Manchester Syntax from TBox data."""
    lines = []
    
    # Prefixes
    lines.append("Prefix: rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>")
    lines.append("Prefix: rdfs: <http://www.w3.org/2000/01/rdf-schema#>")
    lines.append("Prefix: owl: <http://www.w3.org/2002/07/owl#>")
    lines.append("Prefix: xsd: <http://www.w3.org/2001/XMLSchema#>")
    lines.append("Prefix: dc: <http://purl.org/dc/elements/1.1/>")
    lines.append("Prefix: upo: <http://example.org/saturn/upo#>")
    lines.append("")
    
    # Ontology declaration
    domain_safe = domain.replace(" ", "_").replace("-", "_") if domain else "unknown"
    lines.append(f"Ontology: <http://example.org/saturn/upo/federated/{domain_safe}>")
    lines.append("")
    lines.append("Annotations:")
    lines.append(f"    dc:title \"Federated Primitive TBox for {domain}\",")
    lines.append(f"    dc:description \"Layer 1 Federated Primitive TBox generated by Global-Local Agent Collaboration\",")
    lines.append(f"    dc:date \"{datetime.now().strftime('%Y-%m-%d')}\"")
    lines.append("")
    
    # ========== Core Classes ==========
    lines.append("# ==================== Core Structural Elements ====================")
    lines.append("")
    lines.append("Class: upo:Column")
    lines.append("    Annotations: rdfs:label \"Column\"")
    lines.append("    Annotations: rdfs:comment \"Abstract base class for all column types\"")
    lines.append("")
    lines.append("Class: upo:Table")
    lines.append("    Annotations: rdfs:label \"Table\"")
    lines.append("    Annotations: rdfs:comment \"A data table\"")
    lines.append("")
    
    # ========== hasColumn Object Property ==========
    lines.append("# ==================== Object Property ====================")
    lines.append("")
    lines.append("ObjectProperty: upo:hasColumn")
    lines.append("    Annotations: rdfs:label \"hasColumn\"")
    lines.append("    Annotations: rdfs:comment \"Links a Table to its Column\"")
    lines.append("    Domain: upo:Table")
    lines.append("    Range: upo:Column")
    lines.append("")
    
    # ========== Primitive Classes ==========
    lines.append("# ==================== Primitive Classes ====================")
    lines.append("")
    
    for cls in classes:
        name = cls.get("name", "Unknown")
        desc = cls.get("description", "")[:200].replace('"', "'")
        # Support both parent_class and parent_classes
        parent = cls.get("parent_class")
        if not parent:
            parent_classes = cls.get("parent_classes", ["Column"])
            parent = parent_classes[0] if parent_classes else "Column"
        score = aggregated_votes.get(name, 0.0)
        
        lines.append(f"Class: upo:{name}")
        lines.append(f"    Annotations: rdfs:label \"{name}\"")
        lines.append(f"    Annotations: rdfs:comment \"{desc}\"")
        
        # Usefulness score as annotation
        lines.append(f"    Annotations: upo:usefulnessScore \"{score:.3f}\"^^xsd:decimal")
        
        if parent and parent != "Thing":
            lines.append(f"    SubClassOf: upo:{parent}")
        
        lines.append("")
    
    # ========== Data Properties ==========
    lines.append("# ==================== Data Properties ====================")
    lines.append("")
    
    for prop in data_properties:
        name = prop.get("property_name", prop.get("name", "Unknown"))
        desc = prop.get("description", "")[:200].replace('"', "'")
        domain = prop.get("domain", [])
        range_type = prop.get("range_type", "xsd:string")
        functional = prop.get("functional", False)
        readout_template = prop.get("readout_template", "")
        
        lines.append(f"DataProperty: upo:{name}")
        lines.append(f"    Annotations: rdfs:label \"{name}\"")
        lines.append(f"    Annotations: rdfs:comment \"{desc}\"")
        
        # Add readout template if present
        if readout_template:
            # Escape quotes and newlines for OWL annotation
            safe_template = readout_template.replace('"', "'").replace('\n', ' ')[:300]
            lines.append(f"    Annotations: upo:readoutTemplate \"{safe_template}\"")
        
        if domain:
            domain_str = ", ".join([f"upo:{d}" for d in domain])
            lines.append(f"    Domain: {domain_str}")
        
        lines.append(f"    Range: {range_type}")
        
        if functional:
            lines.append("    Characteristics: Functional")
        
        lines.append("")
    
    return "\n".join(lines)


def _generate_report(
    state: FederatedPrimitiveTBoxState,
    classes: List[Dict],
    data_properties: List[Dict],
) -> Dict[str, Any]:
    """Generate JSON summary report."""
    
    # Class ranking by usefulness
    aggregated_votes = state.aggregated_votes or {}
    class_ranking = sorted(
        [(c.get("name"), aggregated_votes.get(c.get("name"), 0.0)) for c in classes],
        key=lambda x: x[1],
        reverse=True
    )
    
    return {
        "metadata": {
            "dataset": state.dataset_name,
            "generated_at": datetime.now().isoformat(),
            "n_iterations": state.n_iterations,
            "actual_iterations": len(state.synthesis_log or []),
        },
        "statistics": {
            "n_clusters": state.n_clusters,
            "n_cqs": len(state.competency_questions or []),
            "n_classes": len(classes),
            "n_data_properties": len(data_properties),
        },
        "class_ranking": [
            {"class_name": name, "usefulness_score": score}
            for name, score in class_ranking
        ],
        "synthesis_history": state.synthesis_log or [],
        # Complete review history with voting for ablation experiments
        "review_history": state.review_log or [],
        "cluster_info": {
            group_id: {
                "n_cqs": len(data.get("cqs", [])),
            }
            for group_id, data in (state.cluster_assignments or {}).items()
        },
    }
