"""
Data Helper Utilities

Provides common data parsing and transformation functions used across the codebase.
This module reduces code duplication and ensures consistent error handling.
"""

import json
from typing import Any, Dict, List, Optional, TypeVar, Union
from loguru import logger

T = TypeVar('T')


def _safe_parse_json(
    value: Any,
    default: T = None,
    expected_type: type = None,
) -> Union[T, Any]:
    """
    Safely parse a JSON string or return the value if already parsed.
    
    Handles:
    - JSON strings -> parsed dict/list
    - Already parsed dicts/lists -> returned as-is
    - numpy arrays -> converted to list
    - None/empty -> returns default
    - Parse errors -> returns default with warning
    
    Args:
        value: The value to parse (str, dict, list, or None)
        default: Default value if parsing fails (default: None)
        expected_type: Optional type check (dict or list)
        
    Returns:
        Parsed value or default
        
    Example:
        >>> safe_parse_json('{"key": "value"}', default={})
        {'key': 'value'}
        >>> safe_parse_json([1, 2, 3], default=[])
        [1, 2, 3]
        >>> safe_parse_json(None, default={})
        {}
    """
    if value is None:
        return default
    
    # Handle numpy arrays
    if hasattr(value, 'tolist'):
        value = value.tolist()
    
    # Already the expected type
    if isinstance(value, (dict, list)):
        if expected_type is not None and not isinstance(value, expected_type):
            return default
        return value
    
    # Parse JSON string
    if isinstance(value, str):
        if not value.strip():
            return default
        
        # Strip markdown code blocks (```json ... ``` or ``` ... ```)
        text = value.strip()
        if text.startswith('```'):
            # Find the end of first line (might be ```json or just ```)
            first_newline = text.find('\n')
            if first_newline > 0:
                text = text[first_newline + 1:]
            # Remove trailing ```
            if text.endswith('```'):
                text = text[:-3].strip()
        
        try:
            parsed = json.loads(text)
            if expected_type is not None and not isinstance(parsed, expected_type):
                return default
            return parsed
        except json.JSONDecodeError as e:
            logger.debug(f"JSON parse failed for value: {value[:100]}... - {e}")
            return default
    
    # Unknown type
    return default


def safe_parse_json_dict(value: Any, default: Optional[Dict] = None) -> Dict:
    """Parse JSON and ensure result is a dict."""
    return _safe_parse_json(value, default=default or {}, expected_type=dict)


def safe_parse_json_list(value: Any, default: Optional[List] = None) -> List:
    """Parse JSON and ensure result is a list."""
    return _safe_parse_json(value, default=default or [], expected_type=list)


def extract_readout_from_column_summary(column_summary: Dict[str, Any]) -> str:
    """
    Extract human-readable readout from column summary's data_property_values.
    
    The readout is generated by the column_summary agent (Stage 2) and stored
    in the data_property_values field. This function extracts and combines
    all available readouts for use in Stage 4 summarization.
    
    Args:
        column_summary: Column summary dict from LanceDB
        
    Returns:
        Combined readout string or empty string if not available
        
    Example:
        >>> summary = {'data_property_values': '[{"readout": "Range: 1990-2024"}]'}
        >>> extract_readout_from_column_summary(summary)
        'Range: 1990-2024'
    """
    dpv = column_summary.get('data_property_values', [])
    
    # Parse if string (from LanceDB storage)
    dpv = safe_parse_json_list(dpv, default=[])
    
    # Collect all readouts
    readouts = []
    for item in dpv:
        if isinstance(item, dict) and 'readout' in item:
            readout = (item.get('readout') or '').strip()
            if readout:
                readouts.append(readout)
    
    return "; ".join(readouts) if readouts else ""
