#!/usr/bin/env python3
"""
Compute P@K metrics from Solo prediction files.

This script reads prediction files generated by Solo's finetune_table_retr.py
and computes Precision@K for K = 1, 3, 5, 10, 20, 100.

Handles edge cases where the number of tables is less than K.
"""

import json
import argparse
import sys
from pathlib import Path
from collections import defaultdict


def compute_precision_at_k(predictions: list, k_values: list = [1, 3, 5, 10, 20, 100]) -> dict:
    """
    Compute P@K for given predictions.
    
    Args:
        predictions: List of prediction items, each containing:
            - table_id_lst: Ground truth table IDs (list)
            - ctxs: Retrieved contexts in ranked order (list of dicts with 'tag' containing 'table_id')
              OR tags: Retrieved tables in ranked order (list of dicts with 'table_id')
        k_values: List of K values to compute P@K for
    
    Returns:
        Dictionary with 'p@k' keys and values containing:
            - value: P@K percentage
            - hits: Number of hits
            - total: Total queries
            - valid: Whether K is valid (enough retrieved tables)
    """
    results = {}
    n_queries = len(predictions)
    
    if n_queries == 0:
        for k in k_values:
            results[f'p@{k}'] = {'value': 0.0, 'hits': 0, 'total': 0, 'valid': False}
        return results
    
    for k in k_values:
        hits = 0
        valid_queries = 0
        
        for pred in predictions:
            gold_tables = set(pred.get('table_id_lst', []))
            if not gold_tables:
                # Fallback to single table_id if table_id_lst not present
                single_table = pred.get('table_id')
                if single_table:
                    gold_tables = {single_table}
            
            # Get top-K retrieved tables - support both 'ctxs' (with 'tag') and 'tags' format
            retrieved_tables = []
            seen_tables = set()
            
            # Try 'ctxs' format first (each ctx has a 'tag' with 'table_id')
            ctxs = pred.get('ctxs', [])
            if ctxs:
                for ctx in ctxs:
                    tag = ctx.get('tag', {})
                    table_id = tag.get('table_id') if isinstance(tag, dict) else None
                    if table_id and table_id not in seen_tables:
                        seen_tables.add(table_id)
                        retrieved_tables.append(table_id)
                        if len(retrieved_tables) >= k:
                            break
            else:
                # Fallback to 'tags' format (direct list of tag dicts)
                tags = pred.get('tags', [])
                for tag in tags:
                    table_id = tag.get('table_id')
                    if table_id and table_id not in seen_tables:
                        seen_tables.add(table_id)
                        retrieved_tables.append(table_id)
                        if len(retrieved_tables) >= k:
                            break
            
            # Check if we have enough retrieved tables for this K
            if len(retrieved_tables) < k:
                # Still count the query, but check among available tables
                pass
            
            valid_queries += 1
            
            # Check if any gold table is in top-K retrieved
            top_k_tables = set(retrieved_tables[:k])
            if gold_tables & top_k_tables:
                hits += 1
        
        results[f'p@{k}'] = {
            'value': 100.0 * hits / n_queries if n_queries > 0 else 0.0,
            'hits': hits,
            'total': n_queries,
            'valid': True
        }
    
    return results


def get_table_count(predictions: list) -> int:
    """Get the number of unique tables in the dataset."""
    tables = set()
    for pred in predictions:
        # Support both 'ctxs' format (with 'tag') and 'tags' format
        ctxs = pred.get('ctxs', [])
        if ctxs:
            for ctx in ctxs:
                tag = ctx.get('tag', {})
                table_id = tag.get('table_id') if isinstance(tag, dict) else None
                if table_id:
                    tables.add(table_id)
        else:
            tags = pred.get('tags', [])
            for tag in tags:
                table_id = tag.get('table_id')
                if table_id:
                    tables.add(table_id)
    return len(tables)


def load_predictions(pred_file: str) -> list:
    """Load predictions from JSONL file."""
    predictions = []
    with open(pred_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    pred = json.loads(line)
                    predictions.append(pred)
                except json.JSONDecodeError as e:
                    print(f"Warning: Failed to parse line: {e}", file=sys.stderr)
    return predictions


def format_results(results: dict, table_count: int, k_values: list = [1, 3, 5, 10, 20, 100]) -> str:
    """Format results for human-readable output."""
    lines = []
    lines.append(f"Total tables: {table_count}")
    lines.append("")
    
    for k in k_values:
        key = f'p@{k}'
        if key in results:
            r = results[key]
            if k > table_count:
                lines.append(f"P@{k}: N/A (only {table_count} tables)")
            else:
                lines.append(f"P@{k}: {r['value']:.2f}% ({r['hits']}/{r['total']})")
    
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description='Compute P@K metrics from Solo predictions')
    parser.add_argument('pred_file', help='Path to prediction JSONL file')
    parser.add_argument('--output', '-o', help='Output JSON file for metrics')
    parser.add_argument('--k-values', nargs='+', type=int, default=[1, 3, 5, 10, 20, 100],
                        help='K values for P@K (default: 1 3 5 10 20 100)')
    parser.add_argument('--json', action='store_true', help='Output in JSON format')
    
    args = parser.parse_args()
    
    # Load predictions
    predictions = load_predictions(args.pred_file)
    if not predictions:
        print(f"Error: No predictions found in {args.pred_file}", file=sys.stderr)
        sys.exit(1)
    
    # Compute metrics
    results = compute_precision_at_k(predictions, args.k_values)
    table_count = get_table_count(predictions)
    
    # Add table count to results
    results['table_count'] = table_count
    results['query_count'] = len(predictions)
    
    # Output
    if args.json:
        print(json.dumps(results, indent=2))
    else:
        print(format_results(results, table_count, args.k_values))
    
    # Save to file if requested
    if args.output:
        with open(args.output, 'w', encoding='utf-8') as f:
            json.dump(results, f, indent=2)
        print(f"\nMetrics saved to: {args.output}")


if __name__ == '__main__':
    main()
